### ISSUE TITLE
Node to Composition Link with an sh:inversePath is not working

### ISSUE THREAD

**Issue by BenjaminHofstetter** [zazuko/blueprint#26]
Node to Composition Link is not working if the path from the Connection point to the Node is an inverse path.

```ttl

#
#  Now we want to see the Datasete Root and the Vocabs used without the cube version node
flux:VacabularyToDatasetRootTreeLink a fluxSchema:CompositionToNodeLink ;
   sh:targetClass flux:DatasetRootTree ;           # the target class is the targetClass of the SHACL Shape - but the source of our link
   fluxSchema:target dms:Vocabulary ;               # this is the target of our link - the dms:Vocabulary
   rdfs:label "Used Vacabulary" ;             # a label we can show in the UI
   fluxSchema:inverseLabel "Vacabulary is Used in" ;       # if we see the link in the opposite direction we show this label
    # there is one inks between a DatasetRootTree and an Vocabulary
   sh:property [
       sh:targetClass dms:Cube ;                         # the source of the link (connection point Cube)
       sh:path [
           sh:inversePath cube-meta:isUsedIn 
       ] ;    # the path to follow to reach the target node (the Vacabulary)
       sh:class dms:Vocabulary ;                        # the target class of the instance on the other side of the link
   ] .

```

The resulting query is "valid" but the inverse path translates in the query to a forward path.

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the CompositionToNodeLink class to correctly handle inverse paths when creating queries. This addresses the issue where Node to Composition Links were not working correctly with inverse paths from Connection points to Nodes.

I also created pull request: https://github.com/zazuko/blueprint/pull/27


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
